require("biiku.plugins.lualine")
require("biiku.plugins.treesitter")
require("biiku.plugins.gruvbox")
require("biiku.plugins.nvim-tree")
require("biiku.plugins.lsp")
require("biiku.plugins.alpha")
require("biiku.plugins.barbar")
